### ISSUE TITLE
Label for Country , Province and Cities not shown

### ISSUE THREAD

**Issue by hamedmaleki1366** [fegyi001/osmgwc#1]
hi ,
after following your instruction and creating map preview with GeoFabriks Osm data .
now i cant show Country and Province and Cities Labels (name) ,
but roads names are very well.

what should i do ? 

thank you .

**Comment by AntoineRz** [comment]
In the settlements style css removing [wayarea] things in css solved the problem. This must be linked to the hungarian exemple.
