### ISSUE TITLE
The style file in geoserver 2.16.02

### ISSUE THREAD

**Issue by iamtekson** [fegyi001/osmgwc#2]
I think geoserver 2.16.02 doesn't support the `css` style. Is there any resources on `sld`?

**Comment by wmiler** [comment]
You will need to install the plugin, see this part of the [manual](https://docs.geoserver.org/stable/en/user/styling/css/install.html)
On linux, the directory works out to `geoserver-2.17.0/webapps/geoserver/WEB-INF/lib`

**Comment by iamtekson** [comment]
Ohh !!! Ok thank you I will check this

**Comment by fegyi001** [comment]
@wmiler thanks for helping out @iamtekson, that is the right way to do it indeed.
