### ISSUE TITLE
Not Able to display railway station names , Restaurants etc like OSM server.

### ISSUE THREAD

**Issue by lalpawan7** [fegyi001/osmgwc#3]
Hey ,
I did all the above steps and all is running great but I am not able to get railway station name , restaurants , etc . These data point were available in OSM but not able to get these in my own geoserver implementation. Any reasons for this?
<img width="1280" alt="Screenshot 2020-06-10 at 2 34 36 AM" src="https://user-images.githubusercontent.com/30041590/84199588-0eb04880-aac3-11ea-9d7c-f7580330810a.png">

**Comment by fegyi001** [comment]
Hello @lalpawan7 and thanks for the comment. There is no layer for POI data such as restaurants, station names etc.  These are usually point features, and I did visualization only for polygon and polyline features. You should make your own that fit your needs. This is not difficult at all, I recommend the GeoServer docs here: https://docs.geoserver.org/latest/en/user/styling/css/cookbook/point.html

**Comment by lalpawan7** [comment]
Thanks for early reply @fegyi001 .
I am new to GIS application(only 2 weeks).
Can you tell me which table(out of 18 we have created ) has point features such as restaurant, hospitals, super market, church,etc so that I can apply individual style to each one of them.

**Comment by fegyi001** [comment]
There is none. I just did not create those tables. You should create your own PostGIS tables (see create_separate_tables.sql for examples).

**Comment by lalpawan7** [comment]
Thanks @fegyi001 . If you could just give one example SQL query  for creating (hospital). I will be grateful.
